ViewModels/Office/HopelifeVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Insurancedirect.ViewModels.Office
{
    public class HopelifeVM
    {
    }
}

ViewModels/Office/PreviewinfoVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Insurancedirect.ViewModels.Office
{
    public class PreviewinfoVM
    {
        public theclockVM theclock { get; set; }
        public HopelifeVM hopelife { get; set; }

        public PreviewinfoVM(){
            this.theclock = new theclockVM();
            this.hopelife = new HopelifeVM();
                   }
    }
}

ViewModels/Office/theclockVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Insurancedirect.ViewModels.Office
{
    public class theclockVM
    {
        public int SN { get; set; }


        [Required]
        public string Insuredname { get; set; }
      [Required]
        public string Vehicle_Insurance_class { get; set; }
        [Required]
        public string Vehicle_make { get; set; }
        [Required]
        public string Vehicle_model { get; set; }
        [Required]
        public string Vehicle_year { get; set; }
        [Required]
        public string Registeration_number { get; set; }
        public string Engine_number { get; set; }
        [Required]
        public string Chasis_number { get; set; }
        [Required]
        public string Colour { get; set; }
        [Required]
        public string Usage { get; set; }

        public string Track_comp_name { get; set; }
        public string Track_comp_phone { get; set; }
        public string Track_comp_address { get; set; }
    }
}

Controllers/OfficeController.cs
using Insurancedirect.Data.Entites;
using Insurancedirect.Data.Othermodules;
using Insurancedirect.Data.Servicelayer;
using Insurancedirect.ViewModels.Office;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Insurancedirect.Controllers
{
    [Filters.Authorizesession]
    public class OfficeController : Controller
    {
        // GET: UserHome
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Theclock()
        {
            theclockVM vm = new theclockVM();
            var insured = new Cls_Registration().GetuserbyID(Session["userid"].ToString());
            vm.Insuredname = insured.Firstname + " " + insured.Lastname;
            vm.Vehicle_Insurance_class = "Third party Only";
            ViewBag.insuranceclass = new Filldropdownhelper().FillInsuranceclass();
            ViewBag.vehiclemakes = new Filldropdownhelper().Fillcarmakes();
            var years = new ModDrive().Getlistofyears();

            ViewBag.years = new SelectList(years);
            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Theclock(theclockVM vm)
        {
            if(ModelState.IsValid)
            {
                //put all data in session and redirect to preview page
                Session["insuredname"] = vm.Insuredname;
                Session["vehiclemake"] = vm.Vehicle_make;
                Session["vehiclemodel"] = vm.Vehicle_model;
                Session["vehicleyear"] = vm.Vehicle_year;
                Session["Vehicle_Insurance_class"] = vm.Vehicle_Insurance_class;
              
                Session["registrationnumber"] = vm.Registeration_number;
                Session["Usage"] = vm.Usage;
                Session["Engine_number"] = vm.Engine_number;
                Session["Colour"] = vm.Colour;
                Session["Chasis_number"] = vm.Chasis_number;
                Session["track_comp_name"] = vm.Track_comp_name;
                Session["track_comp_address"] = vm.Track_comp_address;
                Session["track_comp_phone"] = vm.Track_comp_phone;
                Session["producttype"] = "TC";
                return Redirect("/Office/Previewinfo");
               
            }
            var insured = new Cls_Registration().GetuserbyID(Session["userid"].ToString());
            vm.Insuredname = insured.Firstname + " " + insured.Lastname;
            ViewBag.insuranceclass = new Filldropdownhelper().FillInsuranceclass();
            ViewBag.vehiclemakes = new Filldropdownhelper().Fillcarmakes();
            var years = new ModDrive().Getlistofyears();

            ViewBag.years = new SelectList(years);
            return View(vm);
        }

        public ActionResult Previewinfo()
        {


            // pass productype querystring to viewbag for view
            string type = Session["producttype"].ToString();
            ViewBag.producttype = type;
             switch (type)
                {
                    case "TC":
                        PreviewinfoVM vm = new PreviewinfoVM();

                        string insuredname = Session["insuredname"].ToString();
                        vm.theclock.Insuredname = insuredname;
                        vm.theclock.Chasis_number = Session["Chasis_number"].ToString();
                        vm.theclock.Colour = Session["Colour"].ToString();
                        vm.theclock.Engine_number = Session["Engine_number"].ToString();
                        vm.theclock.Registeration_number = Session["registrationnumber"].ToString();
                        vm.theclock.Usage = Session["Usage"].ToString();
                        vm.theclock.Vehicle_Insurance_class = Session["Vehicle_Insurance_class"].ToString();
                        vm.theclock.Vehicle_make = Session["vehiclemake"].ToString();
                        vm.theclock.Vehicle_model = Session["vehiclemodel"].ToString();
                        vm.theclock.Vehicle_year = Session["vehicleyear"].ToString();
                    vm.theclock.Track_comp_name = Session["track_comp_name"].ToString();
                    vm.theclock.Track_comp_address = Session["track_comp_address"].ToString();
                    vm.theclock.Track_comp_phone = Session["track_comp_phone"].ToString();
                    return View(vm);

                    case "HL":
                        PreviewinfoVM info = new PreviewinfoVM();
                        return View(info);
                    default:
                        break;
                }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Previewinfo(PreviewinfoVM vm)
        {
            var type = Session["producttype"].ToString();
            switch (type)
            {
                case "TC":
                    //pass parameters from session to the clock view model for save and email 
                    string insuredname = Session["insuredname"].ToString();
                    vm.theclock.Insuredname = insuredname;
                    vm.theclock.Chasis_number = Session["Chasis_number"].ToString();
                    vm.theclock.Colour = Session["Colour"].ToString();
                    vm.theclock.Engine_number = Session["Engine_number"].ToString();
                    vm.theclock.Registeration_number = Session["registrationnumber"].ToString();
                    vm.theclock.Usage = Session["Usage"].ToString();
                    vm.theclock.Vehicle_Insurance_class = Session["Vehicle_Insurance_class"].ToString();
                    vm.theclock.Vehicle_make = Session["vehiclemake"].ToString();
                    vm.theclock.Vehicle_model = Session["vehiclemodel"].ToString();
                    vm.theclock.Vehicle_year = Session["vehicleyear"].ToString();
                    vm.theclock.Track_comp_name = Session["track_comp_name"].ToString();
                    vm.theclock.Track_comp_address = Session["track_comp_address"].ToString();
                    vm.theclock.Track_comp_phone = Session["track_comp_phone"].ToString();
                    var res = new Cls_Policies().Inserttheclockpolicy(vm.theclock);
                    if(res.ErrorCode == 0)
                    {
                        //send email
                        ModDrive mod = new ModDrive();
                        var user = new Cls_Registration().GetuserbyID(mod.Getcurrentuser());
                         //string body = mod.PopulateBodyproductsuccessful(mod.Getcurrentuserfirstname(), "The Clock");
                            //mod.SendHtmlFormattedEmail(user.Email, "", "Your Policy has been created!", body);
                        TempData["success"] = "true";
                        TempData["message"] = "Your Policy registration has been successfull. You will get notified within 1-3 days to complete your purchase as soon as all background checks has been completed. You can always view the status and progress of your policies here.";
                       return RedirectToAction("policies");

                    }
                    else
                    {
                        return Redirect("/Home/error");
                    }
                    

                case "HL":
                    //theclockVM vm = new theclockVM();
                    //vm.Insuredname = Session["insuredname"].ToString();
                    //vm.Chasis_number = Session["Chasis_number"].ToString();
                    //vm.Colour = Session["Colour"].ToString();
                    //vm.Engine_number = Session["Engine_number"].ToString();
                    //vm.Registeration_number = Session["registrationnumber"].ToString();
                    //vm.Usage = Session["Usage"].ToString();
                    //vm.Vehicle_Insurance_class = Session["Vehicle_Insurance_class"].ToString();
                    //vm.Vehicle_make = Session["vehiclemake"].ToString();
                    //vm.Vehicle_model = Session["vehiclemodel"].ToString();
                    //vm.Vehicle_year = Session["vehicleyear"].ToString();
                    break;


            }
            return View();
        }
        public ActionResult Policies()
        {
            ModDrive mod = new ModDrive();
            var Policies = new Cls_Policies().Getpolicybyuser(mod.Getcurrentuser());

            return View(Policies);
        }

        public ActionResult Sidepoliciesview()
        {
            ModDrive mod = new ModDrive();
            var Policies = new Cls_Policies().Getpolicybyuser(mod.Getcurrentuser());

            return PartialView("_Sideofficenav", Policies);
        }
        public ActionResult Transactions()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return Redirect("/");
        }


        public JsonResult GetvehicleMakeBrand(string makeid)
        {
            List<VehMakeBrand> brands = new Cls_Vehiclemakebrands().GetvehiclebrandByMake(makeid);

            return Json(brands, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Office/Policies.cshtml
@model IEnumerable<Insurancedirect.Data.Entites.Policy>

@{
    ViewBag.Title = "Policies";
}


<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">My Policies</h4>
    </div>
</div>
@{Html.RenderPartial("_messagepanelPartial");}

<div class="row">
    <div class="col-md-8">



        @if (Model.Count() == 0)
        {
            <div class="card-box">
                <strong class="text-primary">You have no existing policies yet. <a href="/Office/Dashboard" class="btn btn-primary">Create new Policy</a></strong>

            </div>
        }
        else
        {
            foreach (var item in Model)
            {

                if (item.ProductID == "TC")
                {
                    <div class="card-box">
                        <div class="">

                            <div class="form-group row">
                                <strong class="text-small col-md-2">Insured Name:</strong>
                                <div class="col-md-2">
                                    <span class="text-upper">@item.Insuredname</span>
                                </div>
                                <strong class="col-md-2">Started on:</strong>
                                <div class="col-md-2">
                                    <span class="text-upper">@item.Effective_date.Value.ToString("dd MMM yyyy")</span>
                                </div>
                                <div class="col-md-2">
                                    <strong>Status: </strong>
                                </div>
                                <div class="col-md-2">
                                    <span class="badge badge-primary">AWAITING CONFIRMATION</span>
                                </div>

                            </div>




                            <div class="form-group row">
                                <strong class="col-md-2">Policy name:</strong>
                                <div class="col-md-2">
                                    <span class="text-upper">@item.Productname</span>
                                </div>
                                <div class="col-form-label col-md-2">
                                    <strong>Biz option: </strong>
                                </div>
                                <div class="col-md-2">
                                    <span class="badge badge-success">NEW</span>
                                </div>
                                <strong class=" col-md-2">Expired On:</strong>
                                <div class="col-md-2">
                                    <span class="text-upper">@item.Expiry_date.Value.ToString("dd MMM yyyy")</span>
                                </div>
                            </div>

                            <div class="form-group row">

                                <div class="col-md-2">
                                    <strong>Policy number: </strong>
                                </div>
                                <div class="col-md-3">
                                    @if (item.Policyno == "")
                                    {
                                        <span class="badge badge-danger">AWAITING CONFIRMATION</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-primary">@item.Policyno</span>
                                    }
                                </div>
                            </div>

                            <div class="form-group row">

                                <div class="col-md-10">
                                    <div class="text-center">
                                        <a class="btn btn-primary" href="/Office/Policydetails/@item.DocumentID">View Details <i class="fa fa-arrow-circle-right"></i></a>
                                    </div>
                                </div>
                            </div>


                        </div>











                    </div>

                }
                //if hope life render different view

            }

        }

        <div class="card-box text-center">
            <strong class="text-primary"><i class="fa fa-plus"></i> <a href="/Office/Dashboard" class="link">Create new Policy</a></strong>

        </div>

    </div>

    @{ Html.RenderAction("Sidepoliciesview", "Office");}


</div>

Views/Office/Previewinfo.cshtml
@model Insurancedirect.ViewModels.Office.PreviewinfoVM

@{
    ViewBag.Title = "Previewinfo";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Buy <strong class="text-success">TheClock™</strong>  Policy</h4>
    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "myform" }))
{
    @Html.AntiForgeryToken()

<div class="row">
    <div class="col-md-8">
        <div class="card-box">
            <h4 class="card-title">Preview Your Information</h4>


            @{Html.RenderPartial("_ProgressSpin");}

            @{Html.RenderPartial("_messagepanelPartial");}



            @if (ViewBag.producttype == "TC")
            {

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Insuredname</label>
                    <div class="col-md-7">

                        <strong class="text-success">@Html.DisplayFor(m => m.theclock.Insuredname)</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Vehicle Insurance Class</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Vehicle_Insurance_class</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Vehicle Make</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Vehicle_make</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Vehicle Model</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Vehicle_model</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Vehicle Year</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Vehicle_year</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Registration number</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Registeration_number</strong>
                    </div>
                </div>


                <div class="form-group row">
                    <label class="col-form-label col-md-3">Engine number</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Engine_number</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Colour</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Colour</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Chasis number</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Chasis_number</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Usage</label>
                    <div class="col-md-7">
                        <strong class="text-success text-bold">@Model.theclock.Usage</strong>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Vehicle Tracking company name</label>
                    <div class="col-md-7">
                        @if (Model.theclock.Track_comp_name != "")
                        {
                            <strong class="text-success text-bold">@Model.theclock.Track_comp_name</strong>
                        }
                        else
                        {
                            <strong class="text-success text-bold">N/A</strong>
                        }

                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Tracking company Address</label>
                    <div class="col-md-7">
                        @if (Model.theclock.Track_comp_address != "")
                        {
                            <strong class="text-success text-bold">@Model.theclock.Track_comp_address</strong>
                        }
                        else
                        {
                            <strong class="text-success text-bold">N/A</strong>
                        }

                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-md-3">Tracking company Phone no.</label>
                    <div class="col-md-7">
                        @if (Model.theclock.Track_comp_phone != "")
                        {
                            <strong class="text-success text-bold">@Model.theclock.Track_comp_phone</strong>
                        }
                        else
                        {
                            <strong class="text-success text-bold">N/A</strong>
                        }

                    </div>
                </div>
            }
            else if (ViewBag.producttype == "HL")
            {

            }

            <div class="form-group row">

                <div class="col-md-10">
                    <div class="text-center">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            </div>


        </div>
    </div>

    @{ Html.RenderAction("Sidepoliciesview", "Office");}


</div>


}

Views/Office/Theclock.cshtml
@model Insurancedirect.ViewModels.Office.theclockVM

@{
    ViewBag.Title = "Theclock";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Buy <strong class="text-success">TheClock™</strong>  Policy</h4>
    </div>
</div>
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <strong>Note!</strong> Please Complete the registration of your account <a href="#" class="alert-link">Complete registration here!</a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "myform" }))
{
    @Html.AntiForgeryToken()

<div class="row">



    <div class="col-md-8">
        <div class="card-box">
            <h4 class="card-title">Your Vehicle Information</h4>
            <div class="breadcrumb">
                <span><i class="fa fa-info-circle"></i> Please make sure all Vehicle information are typed correctly.</span>
            </div>
            @{Html.RenderPartial("_messagepanelPartial");}
            @{Html.RenderPartial("_ProgressSpin");}
            <div class="form-group row">
                <label class="col-form-label col-md-2">Insuredname</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Insuredname, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.Insuredname, "", new { @class = "text-danger text-small text-upper" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Vehicle make</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Vehicle_make, ViewBag.vehiclemakes as SelectList, "Select Vehicle Make", new { @class = "form-control", @id = "make" })
                    @Html.ValidationMessageFor(model => model.Vehicle_make, "", new { @class = "text-danger text-small" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Vehicle model</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Vehicle_model, new SelectList(" "), "Select Vehicle model", new { @class = "form-control", @id = "brand" })
                    @Html.ValidationMessageFor(model => model.Vehicle_model, "", new { @class = "text-danger text-small" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Vehicle Year</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Vehicle_year, ViewBag.years as SelectList, "Select Vehicle year", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Vehicle_model, "", new { @class = "text-danger text-small" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Insurance class</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Vehicle_Insurance_class, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.Vehicle_Insurance_class, "", new { @class = "text-danger text-small" })
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Usage</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Usage, ViewBag.insuranceclass as List<SelectListItem>, "select Insurance class", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Usage, "", new { @class = "text-danger text-small" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-md-2">Registration number</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Registeration_number, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Registeration_number, "", new { @class = "text-danger text-small" })
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Engine number</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Engine_number, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Engine_number, "", new { @class = "text-danger text-small" })
                </div>
            </div>


            <div class="form-group row">
                <label class="col-form-label col-md-2">Chasis number</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Chasis_number, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Chasis_number, "", new { @class = "text-danger text-small" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-form-label col-md-2">Colour</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Colour, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger text-small" })
                </div>
            </div>
            <div class="card member-panel">
                <div class="card-header bg-success">
                    <a style="color:white;" data-toggle="collapse" class="card-title m-b-0" href="#collapse1">Do you have a vehicle tracking company? <i class="fa fa-2x fa-plus-circle pull-right"></i></a>
                    @*<h4 style="color:white;" class="card-title m-b-0">You have a vehicle tracking company?</h4>*@
                </div>
                <div id="collapse1" class="panel-collapse collapse">
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Company name</label>
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Track_comp_name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Track_comp_name, "", new { @class = "text-danger text-small" })
                            </div>
                            <label class="col-form-label col-md-2">Mobile no.</label>
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Track_comp_phone, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Track_comp_phone, "", new { @class = "text-danger text-small" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Company Address</label>
                            <div class="col-md-4">
                                @Html.TextAreaFor(model => model.Track_comp_address, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Track_comp_address, "", new { @class = "text-danger text-small" })
                            </div>
                          

                        </div>
                    </div>
                </div>
                    
                </div>
                <center>
                    <div class="form-group row">

                        <div class="col-md-12">

                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit <i class="fa fa-arrow-circle-right"></i></button>  <button type="submit" class="btn btn-white">Cancel <i class="fa fa-times-circle"></i></button>
                            </div>

                        </div>

                    </div>
                </center>


            </div>
            </div>
            @{ Html.RenderAction("Sidepoliciesview", "Office");}


        </div>
}

@section scripts
{



    <script>
        $(function () {


            //Automaticllaay bind vehicle brand
            $('#make').on('change', function () {
                var url = '@Url.Content("~/")' + "Office/GetvehicleMakeBrand";
                var ddlsource = "#make";

                $.getJSON(url, { makeid: $(ddlsource).val() }, function (data) {
                    var items = '';
                    $("#brand").empty();
                    $.each(data, function (i, row) {
                        items += "<option value='" + row.Brand + "'>" + row.Brand + "</option>";
                    });
                    $("#brand").html(items);
                });
            });
        });
    </script>


}